# Local prototype values for the terminal game.
anime_list = [
    # Higher Score category
    {
        "title": "Cowboy Bebop",
        "score": 8.75,
        "members": 1900000,
        "episodes": 26,
        "year": 1998,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "Death Note",
        "score": 8.62,
        "members": 4100000,
        "episodes": 37,
        "year": 2006,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "Fullmetal Alchemist: Brotherhood",
        "score": 9.10,
        "members": 3400000,
        "episodes": 64,
        "year": 2009,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "Steins;Gate",
        "score": 9.07,
        "members": 2600000,
        "episodes": 24,
        "year": 2011,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "Attack on Titan",
        "score": 9.05,
        "members": 4000000,
        "episodes": 25,
        "year": 2013,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "Frieren: Beyond Journey's End",
        "score": 9.32,
        "members": 1100000,
        "episodes": 28,
        "year": 2023,
        "type": "TV",
        "runtime_minutes": None,
    },
    # More Popular category
    {
        "title": "Naruto",
        "score": 8.00,
        "members": 2800000,
        "episodes": 220,
        "year": 2002,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "One Piece",
        "score": 8.73,
        "members": 2500000,
        "episodes": 1100,
        "year": 1999,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "Demon Slayer",
        "score": 8.50,
        "members": 3100000,
        "episodes": 26,
        "year": 2019,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "Jujutsu Kaisen",
        "score": 8.58,
        "members": 2700000,
        "episodes": 24,
        "year": 2020,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "My Hero Academia",
        "score": 7.85,
        "members": 3400000,
        "episodes": 13,
        "year": 2016,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "Sword Art Online",
        "score": 7.20,
        "members": 3000000,
        "episodes": 25,
        "year": 2012,
        "type": "TV",
        "runtime_minutes": None,
    },
    # More Episodes category
    {
        "title": "Hunter x Hunter",
        "score": 9.03,
        "members": 2900000,
        "episodes": 148,
        "year": 2011,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "Bleach",
        "score": 8.00,
        "members": 2100000,
        "episodes": 366,
        "year": 2004,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "Gintama",
        "score": 8.95,
        "members": 1100000,
        "episodes": 201,
        "year": 2006,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "Monster",
        "score": 8.88,
        "members": 1200000,
        "episodes": 74,
        "year": 2004,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "Haikyu!!",
        "score": 8.45,
        "members": 1900000,
        "episodes": 85,
        "year": 2014,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "Black Clover",
        "score": 8.15,
        "members": 1800000,
        "episodes": 170,
        "year": 2017,
        "type": "TV",
        "runtime_minutes": None,
    },
    # More Recent category
    {
        "title": "Neon Genesis Evangelion",
        "score": 8.35,
        "members": 1800000,
        "episodes": 26,
        "year": 1995,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "Code Geass",
        "score": 8.70,
        "members": 2200000,
        "episodes": 25,
        "year": 2006,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "Psycho-Pass",
        "score": 8.32,
        "members": 1500000,
        "episodes": 22,
        "year": 2012,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "Vinland Saga",
        "score": 8.75,
        "members": 1600000,
        "episodes": 24,
        "year": 2019,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "Chainsaw Man",
        "score": 8.50,
        "members": 1700000,
        "episodes": 12,
        "year": 2022,
        "type": "TV",
        "runtime_minutes": None,
    },
    {
        "title": "Dandadan",
        "score": 8.55,
        "members": 700000,
        "episodes": 12,
        "year": 2024,
        "type": "TV",
        "runtime_minutes": None,
    },
    # Longer Runtime category (movies only)
    {
        "title": "Spirited Away",
        "score": 8.78,
        "members": 1900000,
        "episodes": 1,
        "year": 2001,
        "type": "Movie",
        "runtime_minutes": 125,
    },
    {
        "title": "Your Name",
        "score": 8.83,
        "members": 3000000,
        "episodes": 1,
        "year": 2016,
        "type": "Movie",
        "runtime_minutes": 106,
    },
    {
        "title": "Princess Mononoke",
        "score": 8.68,
        "members": 1300000,
        "episodes": 1,
        "year": 1997,
        "type": "Movie",
        "runtime_minutes": 134,
    },
    {
        "title": "Akira",
        "score": 8.16,
        "members": 1000000,
        "episodes": 1,
        "year": 1988,
        "type": "Movie",
        "runtime_minutes": 124,
    },
    {
        "title": "A Silent Voice",
        "score": 8.93,
        "members": 2400000,
        "episodes": 1,
        "year": 2016,
        "type": "Movie",
        "runtime_minutes": 130,
    },
    {
        "title": "Redline",
        "score": 8.28,
        "members": 500000,
        "episodes": 1,
        "year": 2009,
        "type": "Movie",
        "runtime_minutes": 102,
    },
]
